spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:4540/marketing
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    password: ''
    port: 3131
    ssl: false
  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: zblashh7@gmail.com
    password: fb19077774+
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
