spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:4540/marketing
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    password: ''
    port: 3131
    ssl: false
  mail:
    debug: true
    host: smtp.xxx.com
    port: 587
    username: xxxxx
    password: xxxxxx
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
