spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  cache:
    type: redis
amazonProperties:
  endpointUrl: https://s3.eu-central-1.amazonaws.com
  accessKey: AKIA4VPKRZHYKEPPQWU3
  secretKey: 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
  bucketName: onlineplasiyer

---

spring:
  profiles: dev
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:4540/marketing
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    password: ''
    port: 3131
    ssl: false
  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: zblashh7@gmail.com
    password: fb19077774+
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


---

spring:
  profiles: prod
  datasource:
    password: vAKj9GgWLLh3Y1MHIEA4
    url: jdbc:postgresql://onlineplasiyerpostgres.c8pqewmiooar.eu-central-1.rds.amazonaws.com:5432/marketing
    username: onlineplasiyer
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    password: ''
    port: 3131
    ssl: false
  mail:
    debug: true
    host: your.mail.host
    port: 111
    username: your.mail.username
    password: your.mail.password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true