spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  cache:
    type: redis
amazonProperties:
  endpointUrl: https://s3.eu-central-1.amazonaws.com
  accessKey: xxxxxxxxxxxxx
  secretKey: xxxxxxxxxxxxx
  bucketName: xxxxxxxxxxxx
